version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - 8001:8001
        volumes:
            - /srv/www/ecom/static:/ecommerce/static/
            - /srv/www/ecom/media:/ecommerce/media
        command: "gunicorn ecommerce.wsgi:application --bind 0.0.0.0:8001"