version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - 8001:8001
        volumes:
            - ./static/:/srv/www/ecom/static
            - ./media:/srv/www/ecom/media
        command: "gunicorn ecommerce.wsgi:application --bind 0.0.0.0:8001"