# Generated by Django 4.2.4 on 2023-09-10 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('-id',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
