# Generated by Django 4.2.4 on 2023-09-03 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specs',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_specs_as_detail', to='catalog.details', verbose_name='Характеристика'),
        ),
    ]
