# Generated by Django 4.2.4 on 2023-09-10 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_products_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default=None, null=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('finished', 'Завершенный'), ('estimating', 'Оценивается'), ('awaiting', 'Ожидает'), ('delivering', 'Доставляется'), ('delivered', 'Доставлен'), ('canceled', 'Отменен'), ('payment', 'Ожидает оплаты'), ('payed', 'Оплачен')], default='new', max_length=25, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('discount', models.FloatField(default=0, verbose_name='Скидка')),
                ('client', models.TextField(blank=True, default=None, null=True, verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(default=0, verbose_name='Стоимость')),
                ('amount', models.IntegerField(default=0, verbose_name='Количество')),
                ('comment', models.TextField(blank=True, default=None, null=True, verbose_name='Комментарий')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='catalog.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='catalog.products', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
                'db_table': 'order_items',
            },
        ),
    ]
