# Generated by Django 4.2.4 on 2023-09-04 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_categories_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='details',
        ),
    ]
