# Generated by Django 4.2.4 on 2023-09-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_categories_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='details',
            field=models.ManyToManyField(blank=True, related_name='categories', to='catalog.details', verbose_name='Характеристики'),
        ),
    ]
