# Generated by Django 4.2.4 on 2023-09-10 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_orders_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='currency',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_orders', to='catalog.currencies', verbose_name='Валюта'),
        ),
    ]
