# Generated by Django 4.2.6 on 2023-10-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_brands_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='source',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Источник данных'),
        ),
        migrations.AddField(
            model_name='products',
            name='source_link',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Карточка товара'),
        ),
    ]
