# Generated by Django 4.2.6 on 2023-10-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_products_source_products_source_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='series',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Серия'),
        ),
    ]
