# Generated by Django 4.2.6 on 2023-10-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_products_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='image_link',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Ссылка на Лого'),
        ),
        migrations.AddField(
            model_name='categories',
            name='image_link',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Ссылка на Лого'),
        ),
    ]
