# Generated by Django 4.2.6 on 2023-10-23 18:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_categories_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True, verbose_name='Описание'),
        ),
    ]
